// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package Report;

public final class CommandOuterClass {
  private CommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    Report.CommandOuterClass.Command.CommandType getType();

    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    java.util.List<Report.CommandOuterClass.Command.Param> 
        getParasList();
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    Report.CommandOuterClass.Command.Param getParas(int index);
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    int getParasCount();
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    java.util.List<? extends Report.CommandOuterClass.Command.ParamOrBuilder> 
        getParasOrBuilderList();
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    Report.CommandOuterClass.Command.ParamOrBuilder getParasOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Report.Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.Command)
      CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      type_ = 0;
      paras_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                paras_ = new java.util.ArrayList<Report.CommandOuterClass.Command.Param>();
                mutable_bitField0_ |= 0x00000002;
              }
              paras_.add(
                  input.readMessage(Report.CommandOuterClass.Command.Param.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          paras_ = java.util.Collections.unmodifiableList(paras_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Report.CommandOuterClass.internal_static_Report_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Report.CommandOuterClass.internal_static_Report_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.CommandOuterClass.Command.class, Report.CommandOuterClass.Command.Builder.class);
    }

    /**
     * Protobuf enum {@code Report.Command.CommandType}
     */
    public enum CommandType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * unillgle
       * </pre>
       *
       * <code>CMT_INVALID = 0;</code>
       */
      CMT_INVALID(0),
      /**
       * <pre>
       * gateway-&gt;web message
       * </pre>
       *
       * <code>CMT_REQ_LOGIN = 1;</code>
       */
      CMT_REQ_LOGIN(1),
      /**
       * <code>CMT_REP_ONLINE = 2;</code>
       */
      CMT_REP_ONLINE(2),
      /**
       * <pre>
       * for mosqitto
       * </pre>
       *
       * <code>CMT_REP_ADD_DEL_DEVICE = 5;</code>
       */
      CMT_REP_ADD_DEL_DEVICE(5),
      /**
       * <pre>
       * for mosqitto
       * </pre>
       *
       * <code>CMT_REP_NOTIFICATION = 6;</code>
       */
      CMT_REP_NOTIFICATION(6),
      /**
       * <code>CMT_REP_SETNAME = 8;</code>
       */
      CMT_REP_SETNAME(8),
      /**
       * <code>CMT_REP_DEL_DEVICE = 10;</code>
       */
      CMT_REP_DEL_DEVICE(10),
      /**
       * <code>CMT_REP_DEVICE_ATTR = 11;</code>
       */
      CMT_REP_DEVICE_ATTR(11),
      /**
       * <code>CMT_REP_DEPLOYMENT = 15;</code>
       */
      CMT_REP_DEPLOYMENT(15),
      /**
       * <pre>
       * only for onoff device
       * </pre>
       *
       * <code>CMT_REP_ONOFF = 19;</code>
       */
      CMT_REP_ONOFF(19),
      /**
       * <pre>
       * unsupport right now
       * </pre>
       *
       * <code>CMT_REP_DEVICE_ONLINE = 21;</code>
       */
      CMT_REP_DEVICE_ONLINE(21),
      /**
       * <pre>
       * unsupport right now only for onoff deivce
       * </pre>
       *
       * <code>CMT_REP_ONOFF_STATUS = 22;</code>
       */
      CMT_REP_ONOFF_STATUS(22),
      /**
       * <code>CMT_REP_DEVICELIST = 2049;</code>
       */
      CMT_REP_DEVICELIST(2049),
      /**
       * <pre>
       * web-&gt;gateway
       * </pre>
       *
       * <code>CMT_REP_LOGIN = 32769;</code>
       */
      CMT_REP_LOGIN(32769),
      /**
       * <code>CMT_REQ_ONLINE = 32770;</code>
       */
      CMT_REQ_ONLINE(32770),
      /**
       * <code>CMT_REQ_SETNAME = 32776;</code>
       */
      CMT_REQ_SETNAME(32776),
      /**
       * <code>CMT_REQ_DEL_DEVICE = 32778;</code>
       */
      CMT_REQ_DEL_DEVICE(32778),
      /**
       * <code>CMT_REQ_DEVICE_ATTR = 32779;</code>
       */
      CMT_REQ_DEVICE_ATTR(32779),
      /**
       * <pre>
       * no feedback
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_IDENTIFY = 32780;</code>
       */
      CMT_REQ_DEVICE_IDENTIFY(32780),
      /**
       * <pre>
       * no feedback for device id = 0x0403 warn
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_WARN = 32781;</code>
       */
      CMT_REQ_DEVICE_WARN(32781),
      /**
       * <code>CMT_REQ_DEPLOYMENT = 32783;</code>
       */
      CMT_REQ_DEPLOYMENT(32783),
      /**
       * <pre>
       * no feedback
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_LEVELCONTROL = 32785;</code>
       */
      CMT_REQ_DEVICE_LEVELCONTROL(32785),
      /**
       * <pre>
       * only for onoff device
       * </pre>
       *
       * <code>CMT_REQ_ONOFF = 32787;</code>
       */
      CMT_REQ_ONOFF(32787),
      /**
       * <pre>
       * unsupport right now
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_ONLINE = 32789;</code>
       */
      CMT_REQ_DEVICE_ONLINE(32789),
      /**
       * <pre>
       * unsupport right now only for onoff deivce
       * </pre>
       *
       * <code>CMT_REQ_ONOFF_STATUS = 32790;</code>
       */
      CMT_REQ_ONOFF_STATUS(32790),
      /**
       * <code>CMT_REQ_DEVICELIST = 34817;</code>
       */
      CMT_REQ_DEVICELIST(34817),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * unillgle
       * </pre>
       *
       * <code>CMT_INVALID = 0;</code>
       */
      public static final int CMT_INVALID_VALUE = 0;
      /**
       * <pre>
       * gateway-&gt;web message
       * </pre>
       *
       * <code>CMT_REQ_LOGIN = 1;</code>
       */
      public static final int CMT_REQ_LOGIN_VALUE = 1;
      /**
       * <code>CMT_REP_ONLINE = 2;</code>
       */
      public static final int CMT_REP_ONLINE_VALUE = 2;
      /**
       * <pre>
       * for mosqitto
       * </pre>
       *
       * <code>CMT_REP_ADD_DEL_DEVICE = 5;</code>
       */
      public static final int CMT_REP_ADD_DEL_DEVICE_VALUE = 5;
      /**
       * <pre>
       * for mosqitto
       * </pre>
       *
       * <code>CMT_REP_NOTIFICATION = 6;</code>
       */
      public static final int CMT_REP_NOTIFICATION_VALUE = 6;
      /**
       * <code>CMT_REP_SETNAME = 8;</code>
       */
      public static final int CMT_REP_SETNAME_VALUE = 8;
      /**
       * <code>CMT_REP_DEL_DEVICE = 10;</code>
       */
      public static final int CMT_REP_DEL_DEVICE_VALUE = 10;
      /**
       * <code>CMT_REP_DEVICE_ATTR = 11;</code>
       */
      public static final int CMT_REP_DEVICE_ATTR_VALUE = 11;
      /**
       * <code>CMT_REP_DEPLOYMENT = 15;</code>
       */
      public static final int CMT_REP_DEPLOYMENT_VALUE = 15;
      /**
       * <pre>
       * only for onoff device
       * </pre>
       *
       * <code>CMT_REP_ONOFF = 19;</code>
       */
      public static final int CMT_REP_ONOFF_VALUE = 19;
      /**
       * <pre>
       * unsupport right now
       * </pre>
       *
       * <code>CMT_REP_DEVICE_ONLINE = 21;</code>
       */
      public static final int CMT_REP_DEVICE_ONLINE_VALUE = 21;
      /**
       * <pre>
       * unsupport right now only for onoff deivce
       * </pre>
       *
       * <code>CMT_REP_ONOFF_STATUS = 22;</code>
       */
      public static final int CMT_REP_ONOFF_STATUS_VALUE = 22;
      /**
       * <code>CMT_REP_DEVICELIST = 2049;</code>
       */
      public static final int CMT_REP_DEVICELIST_VALUE = 2049;
      /**
       * <pre>
       * web-&gt;gateway
       * </pre>
       *
       * <code>CMT_REP_LOGIN = 32769;</code>
       */
      public static final int CMT_REP_LOGIN_VALUE = 32769;
      /**
       * <code>CMT_REQ_ONLINE = 32770;</code>
       */
      public static final int CMT_REQ_ONLINE_VALUE = 32770;
      /**
       * <code>CMT_REQ_SETNAME = 32776;</code>
       */
      public static final int CMT_REQ_SETNAME_VALUE = 32776;
      /**
       * <code>CMT_REQ_DEL_DEVICE = 32778;</code>
       */
      public static final int CMT_REQ_DEL_DEVICE_VALUE = 32778;
      /**
       * <code>CMT_REQ_DEVICE_ATTR = 32779;</code>
       */
      public static final int CMT_REQ_DEVICE_ATTR_VALUE = 32779;
      /**
       * <pre>
       * no feedback
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_IDENTIFY = 32780;</code>
       */
      public static final int CMT_REQ_DEVICE_IDENTIFY_VALUE = 32780;
      /**
       * <pre>
       * no feedback for device id = 0x0403 warn
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_WARN = 32781;</code>
       */
      public static final int CMT_REQ_DEVICE_WARN_VALUE = 32781;
      /**
       * <code>CMT_REQ_DEPLOYMENT = 32783;</code>
       */
      public static final int CMT_REQ_DEPLOYMENT_VALUE = 32783;
      /**
       * <pre>
       * no feedback
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_LEVELCONTROL = 32785;</code>
       */
      public static final int CMT_REQ_DEVICE_LEVELCONTROL_VALUE = 32785;
      /**
       * <pre>
       * only for onoff device
       * </pre>
       *
       * <code>CMT_REQ_ONOFF = 32787;</code>
       */
      public static final int CMT_REQ_ONOFF_VALUE = 32787;
      /**
       * <pre>
       * unsupport right now
       * </pre>
       *
       * <code>CMT_REQ_DEVICE_ONLINE = 32789;</code>
       */
      public static final int CMT_REQ_DEVICE_ONLINE_VALUE = 32789;
      /**
       * <pre>
       * unsupport right now only for onoff deivce
       * </pre>
       *
       * <code>CMT_REQ_ONOFF_STATUS = 32790;</code>
       */
      public static final int CMT_REQ_ONOFF_STATUS_VALUE = 32790;
      /**
       * <code>CMT_REQ_DEVICELIST = 34817;</code>
       */
      public static final int CMT_REQ_DEVICELIST_VALUE = 34817;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CommandType valueOf(int value) {
        return forNumber(value);
      }

      public static CommandType forNumber(int value) {
        switch (value) {
          case 0: return CMT_INVALID;
          case 1: return CMT_REQ_LOGIN;
          case 2: return CMT_REP_ONLINE;
          case 5: return CMT_REP_ADD_DEL_DEVICE;
          case 6: return CMT_REP_NOTIFICATION;
          case 8: return CMT_REP_SETNAME;
          case 10: return CMT_REP_DEL_DEVICE;
          case 11: return CMT_REP_DEVICE_ATTR;
          case 15: return CMT_REP_DEPLOYMENT;
          case 19: return CMT_REP_ONOFF;
          case 21: return CMT_REP_DEVICE_ONLINE;
          case 22: return CMT_REP_ONOFF_STATUS;
          case 2049: return CMT_REP_DEVICELIST;
          case 32769: return CMT_REP_LOGIN;
          case 32770: return CMT_REQ_ONLINE;
          case 32776: return CMT_REQ_SETNAME;
          case 32778: return CMT_REQ_DEL_DEVICE;
          case 32779: return CMT_REQ_DEVICE_ATTR;
          case 32780: return CMT_REQ_DEVICE_IDENTIFY;
          case 32781: return CMT_REQ_DEVICE_WARN;
          case 32783: return CMT_REQ_DEPLOYMENT;
          case 32785: return CMT_REQ_DEVICE_LEVELCONTROL;
          case 32787: return CMT_REQ_ONOFF;
          case 32789: return CMT_REQ_DEVICE_ONLINE;
          case 32790: return CMT_REQ_ONOFF_STATUS;
          case 34817: return CMT_REQ_DEVICELIST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CommandType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
              public CommandType findValueByNumber(int number) {
                return CommandType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Report.CommandOuterClass.Command.getDescriptor().getEnumTypes().get(0);
      }

      private static final CommandType[] VALUES = values();

      public static CommandType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CommandType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Report.Command.CommandType)
    }

    public interface ParamOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Report.Command.Param)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      int getTypeValue();
      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      Report.CommandOuterClass.Command.Param.ParaType getType();

      /**
       * <code>optional uint64 npara = 2;</code>
       */
      long getNpara();

      /**
       * <code>optional double dpara = 3;</code>
       */
      double getDpara();

      /**
       * <code>optional string strpara = 4;</code>
       */
      java.lang.String getStrpara();
      /**
       * <code>optional string strpara = 4;</code>
       */
      com.google.protobuf.ByteString
          getStrparaBytes();

      /**
       * <code>optional bytes bpara = 5;</code>
       */
      com.google.protobuf.ByteString getBpara();
    }
    /**
     * Protobuf type {@code Report.Command.Param}
     */
    public  static final class Param extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Report.Command.Param)
        ParamOrBuilder {
      // Use Param.newBuilder() to construct.
      private Param(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Param() {
        type_ = 0;
        npara_ = 0L;
        dpara_ = 0D;
        strpara_ = "";
        bpara_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Param(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              case 16: {

                npara_ = input.readUInt64();
                break;
              }
              case 25: {

                dpara_ = input.readDouble();
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                strpara_ = s;
                break;
              }
              case 42: {

                bpara_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.CommandOuterClass.internal_static_Report_Command_Param_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.CommandOuterClass.internal_static_Report_Command_Param_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.CommandOuterClass.Command.Param.class, Report.CommandOuterClass.Command.Param.Builder.class);
      }

      /**
       * Protobuf enum {@code Report.Command.Param.ParaType}
       */
      public enum ParaType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>Null = 0;</code>
         */
        Null(0),
        /**
         * <code>UINT8 = 1;</code>
         */
        UINT8(1),
        /**
         * <code>UINT16 = 2;</code>
         */
        UINT16(2),
        /**
         * <code>UINT32 = 3;</code>
         */
        UINT32(3),
        /**
         * <code>UINT64 = 4;</code>
         */
        UINT64(4),
        /**
         * <code>FLOAT = 16;</code>
         */
        FLOAT(16),
        /**
         * <code>DOUBLE = 17;</code>
         */
        DOUBLE(17),
        /**
         * <code>STRING = 32;</code>
         */
        STRING(32),
        /**
         * <code>BYTES = 33;</code>
         */
        BYTES(33),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>Null = 0;</code>
         */
        public static final int Null_VALUE = 0;
        /**
         * <code>UINT8 = 1;</code>
         */
        public static final int UINT8_VALUE = 1;
        /**
         * <code>UINT16 = 2;</code>
         */
        public static final int UINT16_VALUE = 2;
        /**
         * <code>UINT32 = 3;</code>
         */
        public static final int UINT32_VALUE = 3;
        /**
         * <code>UINT64 = 4;</code>
         */
        public static final int UINT64_VALUE = 4;
        /**
         * <code>FLOAT = 16;</code>
         */
        public static final int FLOAT_VALUE = 16;
        /**
         * <code>DOUBLE = 17;</code>
         */
        public static final int DOUBLE_VALUE = 17;
        /**
         * <code>STRING = 32;</code>
         */
        public static final int STRING_VALUE = 32;
        /**
         * <code>BYTES = 33;</code>
         */
        public static final int BYTES_VALUE = 33;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static ParaType valueOf(int value) {
          return forNumber(value);
        }

        public static ParaType forNumber(int value) {
          switch (value) {
            case 0: return Null;
            case 1: return UINT8;
            case 2: return UINT16;
            case 3: return UINT32;
            case 4: return UINT64;
            case 16: return FLOAT;
            case 17: return DOUBLE;
            case 32: return STRING;
            case 33: return BYTES;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ParaType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ParaType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ParaType>() {
                public ParaType findValueByNumber(int number) {
                  return ParaType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return Report.CommandOuterClass.Command.Param.getDescriptor().getEnumTypes().get(0);
        }

        private static final ParaType[] VALUES = values();

        public static ParaType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private ParaType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Report.Command.Param.ParaType)
      }

      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .Report.Command.Param.ParaType type = 1;</code>
       */
      public Report.CommandOuterClass.Command.Param.ParaType getType() {
        Report.CommandOuterClass.Command.Param.ParaType result = Report.CommandOuterClass.Command.Param.ParaType.valueOf(type_);
        return result == null ? Report.CommandOuterClass.Command.Param.ParaType.UNRECOGNIZED : result;
      }

      public static final int NPARA_FIELD_NUMBER = 2;
      private long npara_;
      /**
       * <code>optional uint64 npara = 2;</code>
       */
      public long getNpara() {
        return npara_;
      }

      public static final int DPARA_FIELD_NUMBER = 3;
      private double dpara_;
      /**
       * <code>optional double dpara = 3;</code>
       */
      public double getDpara() {
        return dpara_;
      }

      public static final int STRPARA_FIELD_NUMBER = 4;
      private volatile java.lang.Object strpara_;
      /**
       * <code>optional string strpara = 4;</code>
       */
      public java.lang.String getStrpara() {
        java.lang.Object ref = strpara_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strpara_ = s;
          return s;
        }
      }
      /**
       * <code>optional string strpara = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStrparaBytes() {
        java.lang.Object ref = strpara_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strpara_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int BPARA_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString bpara_;
      /**
       * <code>optional bytes bpara = 5;</code>
       */
      public com.google.protobuf.ByteString getBpara() {
        return bpara_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (type_ != Report.CommandOuterClass.Command.Param.ParaType.Null.getNumber()) {
          output.writeEnum(1, type_);
        }
        if (npara_ != 0L) {
          output.writeUInt64(2, npara_);
        }
        if (dpara_ != 0D) {
          output.writeDouble(3, dpara_);
        }
        if (!getStrparaBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, strpara_);
        }
        if (!bpara_.isEmpty()) {
          output.writeBytes(5, bpara_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (type_ != Report.CommandOuterClass.Command.Param.ParaType.Null.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_);
        }
        if (npara_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(2, npara_);
        }
        if (dpara_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, dpara_);
        }
        if (!getStrparaBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, strpara_);
        }
        if (!bpara_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, bpara_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Report.CommandOuterClass.Command.Param)) {
          return super.equals(obj);
        }
        Report.CommandOuterClass.Command.Param other = (Report.CommandOuterClass.Command.Param) obj;

        boolean result = true;
        result = result && type_ == other.type_;
        result = result && (getNpara()
            == other.getNpara());
        result = result && (
            java.lang.Double.doubleToLongBits(getDpara())
            == java.lang.Double.doubleToLongBits(
                other.getDpara()));
        result = result && getStrpara()
            .equals(other.getStrpara());
        result = result && getBpara()
            .equals(other.getBpara());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + NPARA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNpara());
        hash = (37 * hash) + DPARA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDpara()));
        hash = (37 * hash) + STRPARA_FIELD_NUMBER;
        hash = (53 * hash) + getStrpara().hashCode();
        hash = (37 * hash) + BPARA_FIELD_NUMBER;
        hash = (53 * hash) + getBpara().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Report.CommandOuterClass.Command.Param parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Report.CommandOuterClass.Command.Param parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Report.CommandOuterClass.Command.Param parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Report.CommandOuterClass.Command.Param parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Report.CommandOuterClass.Command.Param prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Report.Command.Param}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Report.Command.Param)
          Report.CommandOuterClass.Command.ParamOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return Report.CommandOuterClass.internal_static_Report_Command_Param_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return Report.CommandOuterClass.internal_static_Report_Command_Param_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Report.CommandOuterClass.Command.Param.class, Report.CommandOuterClass.Command.Param.Builder.class);
        }

        // Construct using Report.CommandOuterClass.Command.Param.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          type_ = 0;

          npara_ = 0L;

          dpara_ = 0D;

          strpara_ = "";

          bpara_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return Report.CommandOuterClass.internal_static_Report_Command_Param_descriptor;
        }

        public Report.CommandOuterClass.Command.Param getDefaultInstanceForType() {
          return Report.CommandOuterClass.Command.Param.getDefaultInstance();
        }

        public Report.CommandOuterClass.Command.Param build() {
          Report.CommandOuterClass.Command.Param result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public Report.CommandOuterClass.Command.Param buildPartial() {
          Report.CommandOuterClass.Command.Param result = new Report.CommandOuterClass.Command.Param(this);
          result.type_ = type_;
          result.npara_ = npara_;
          result.dpara_ = dpara_;
          result.strpara_ = strpara_;
          result.bpara_ = bpara_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Report.CommandOuterClass.Command.Param) {
            return mergeFrom((Report.CommandOuterClass.Command.Param)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Report.CommandOuterClass.Command.Param other) {
          if (other == Report.CommandOuterClass.Command.Param.getDefaultInstance()) return this;
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (other.getNpara() != 0L) {
            setNpara(other.getNpara());
          }
          if (other.getDpara() != 0D) {
            setDpara(other.getDpara());
          }
          if (!other.getStrpara().isEmpty()) {
            strpara_ = other.strpara_;
            onChanged();
          }
          if (other.getBpara() != com.google.protobuf.ByteString.EMPTY) {
            setBpara(other.getBpara());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Report.CommandOuterClass.Command.Param parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Report.CommandOuterClass.Command.Param) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int type_ = 0;
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Report.CommandOuterClass.Command.Param.ParaType getType() {
          Report.CommandOuterClass.Command.Param.ParaType result = Report.CommandOuterClass.Command.Param.ParaType.valueOf(type_);
          return result == null ? Report.CommandOuterClass.Command.Param.ParaType.UNRECOGNIZED : result;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Builder setType(Report.CommandOuterClass.Command.Param.ParaType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .Report.Command.Param.ParaType type = 1;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }

        private long npara_ ;
        /**
         * <code>optional uint64 npara = 2;</code>
         */
        public long getNpara() {
          return npara_;
        }
        /**
         * <code>optional uint64 npara = 2;</code>
         */
        public Builder setNpara(long value) {
          
          npara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 npara = 2;</code>
         */
        public Builder clearNpara() {
          
          npara_ = 0L;
          onChanged();
          return this;
        }

        private double dpara_ ;
        /**
         * <code>optional double dpara = 3;</code>
         */
        public double getDpara() {
          return dpara_;
        }
        /**
         * <code>optional double dpara = 3;</code>
         */
        public Builder setDpara(double value) {
          
          dpara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double dpara = 3;</code>
         */
        public Builder clearDpara() {
          
          dpara_ = 0D;
          onChanged();
          return this;
        }

        private java.lang.Object strpara_ = "";
        /**
         * <code>optional string strpara = 4;</code>
         */
        public java.lang.String getStrpara() {
          java.lang.Object ref = strpara_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            strpara_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public com.google.protobuf.ByteString
            getStrparaBytes() {
          java.lang.Object ref = strpara_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            strpara_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public Builder setStrpara(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          strpara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public Builder clearStrpara() {
          
          strpara_ = getDefaultInstance().getStrpara();
          onChanged();
          return this;
        }
        /**
         * <code>optional string strpara = 4;</code>
         */
        public Builder setStrparaBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          strpara_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString bpara_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes bpara = 5;</code>
         */
        public com.google.protobuf.ByteString getBpara() {
          return bpara_;
        }
        /**
         * <code>optional bytes bpara = 5;</code>
         */
        public Builder setBpara(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          bpara_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes bpara = 5;</code>
         */
        public Builder clearBpara() {
          
          bpara_ = getDefaultInstance().getBpara();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:Report.Command.Param)
      }

      // @@protoc_insertion_point(class_scope:Report.Command.Param)
      private static final Report.CommandOuterClass.Command.Param DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Report.CommandOuterClass.Command.Param();
      }

      public static Report.CommandOuterClass.Command.Param getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Param>
          PARSER = new com.google.protobuf.AbstractParser<Param>() {
        public Param parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Param(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Param> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Param> getParserForType() {
        return PARSER;
      }

      public Report.CommandOuterClass.Command.Param getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .Report.Command.CommandType type = 1;</code>
     */
    public Report.CommandOuterClass.Command.CommandType getType() {
      Report.CommandOuterClass.Command.CommandType result = Report.CommandOuterClass.Command.CommandType.valueOf(type_);
      return result == null ? Report.CommandOuterClass.Command.CommandType.UNRECOGNIZED : result;
    }

    public static final int PARAS_FIELD_NUMBER = 2;
    private java.util.List<Report.CommandOuterClass.Command.Param> paras_;
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public java.util.List<Report.CommandOuterClass.Command.Param> getParasList() {
      return paras_;
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public java.util.List<? extends Report.CommandOuterClass.Command.ParamOrBuilder> 
        getParasOrBuilderList() {
      return paras_;
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public int getParasCount() {
      return paras_.size();
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public Report.CommandOuterClass.Command.Param getParas(int index) {
      return paras_.get(index);
    }
    /**
     * <code>repeated .Report.Command.Param paras = 2;</code>
     */
    public Report.CommandOuterClass.Command.ParamOrBuilder getParasOrBuilder(
        int index) {
      return paras_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Report.CommandOuterClass.Command.CommandType.CMT_INVALID.getNumber()) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < paras_.size(); i++) {
        output.writeMessage(2, paras_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Report.CommandOuterClass.Command.CommandType.CMT_INVALID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < paras_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, paras_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Report.CommandOuterClass.Command)) {
        return super.equals(obj);
      }
      Report.CommandOuterClass.Command other = (Report.CommandOuterClass.Command) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getParasList()
          .equals(other.getParasList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getParasCount() > 0) {
        hash = (37 * hash) + PARAS_FIELD_NUMBER;
        hash = (53 * hash) + getParasList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Report.CommandOuterClass.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.CommandOuterClass.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.CommandOuterClass.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.CommandOuterClass.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.CommandOuterClass.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.CommandOuterClass.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.CommandOuterClass.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Report.CommandOuterClass.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.CommandOuterClass.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.CommandOuterClass.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Report.CommandOuterClass.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.Command)
        Report.CommandOuterClass.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.CommandOuterClass.internal_static_Report_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.CommandOuterClass.internal_static_Report_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.CommandOuterClass.Command.class, Report.CommandOuterClass.Command.Builder.class);
      }

      // Construct using Report.CommandOuterClass.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParasFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (parasBuilder_ == null) {
          paras_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          parasBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Report.CommandOuterClass.internal_static_Report_Command_descriptor;
      }

      public Report.CommandOuterClass.Command getDefaultInstanceForType() {
        return Report.CommandOuterClass.Command.getDefaultInstance();
      }

      public Report.CommandOuterClass.Command build() {
        Report.CommandOuterClass.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Report.CommandOuterClass.Command buildPartial() {
        Report.CommandOuterClass.Command result = new Report.CommandOuterClass.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        if (parasBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            paras_ = java.util.Collections.unmodifiableList(paras_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.paras_ = paras_;
        } else {
          result.paras_ = parasBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Report.CommandOuterClass.Command) {
          return mergeFrom((Report.CommandOuterClass.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Report.CommandOuterClass.Command other) {
        if (other == Report.CommandOuterClass.Command.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (parasBuilder_ == null) {
          if (!other.paras_.isEmpty()) {
            if (paras_.isEmpty()) {
              paras_ = other.paras_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParasIsMutable();
              paras_.addAll(other.paras_);
            }
            onChanged();
          }
        } else {
          if (!other.paras_.isEmpty()) {
            if (parasBuilder_.isEmpty()) {
              parasBuilder_.dispose();
              parasBuilder_ = null;
              paras_ = other.paras_;
              bitField0_ = (bitField0_ & ~0x00000002);
              parasBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParasFieldBuilder() : null;
            } else {
              parasBuilder_.addAllMessages(other.paras_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Report.CommandOuterClass.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Report.CommandOuterClass.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Report.CommandOuterClass.Command.CommandType getType() {
        Report.CommandOuterClass.Command.CommandType result = Report.CommandOuterClass.Command.CommandType.valueOf(type_);
        return result == null ? Report.CommandOuterClass.Command.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Builder setType(Report.CommandOuterClass.Command.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Report.Command.CommandType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Report.CommandOuterClass.Command.Param> paras_ =
        java.util.Collections.emptyList();
      private void ensureParasIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          paras_ = new java.util.ArrayList<Report.CommandOuterClass.Command.Param>(paras_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Report.CommandOuterClass.Command.Param, Report.CommandOuterClass.Command.Param.Builder, Report.CommandOuterClass.Command.ParamOrBuilder> parasBuilder_;

      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public java.util.List<Report.CommandOuterClass.Command.Param> getParasList() {
        if (parasBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paras_);
        } else {
          return parasBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public int getParasCount() {
        if (parasBuilder_ == null) {
          return paras_.size();
        } else {
          return parasBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.CommandOuterClass.Command.Param getParas(int index) {
        if (parasBuilder_ == null) {
          return paras_.get(index);
        } else {
          return parasBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder setParas(
          int index, Report.CommandOuterClass.Command.Param value) {
        if (parasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParasIsMutable();
          paras_.set(index, value);
          onChanged();
        } else {
          parasBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder setParas(
          int index, Report.CommandOuterClass.Command.Param.Builder builderForValue) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.set(index, builderForValue.build());
          onChanged();
        } else {
          parasBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(Report.CommandOuterClass.Command.Param value) {
        if (parasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParasIsMutable();
          paras_.add(value);
          onChanged();
        } else {
          parasBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(
          int index, Report.CommandOuterClass.Command.Param value) {
        if (parasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParasIsMutable();
          paras_.add(index, value);
          onChanged();
        } else {
          parasBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(
          Report.CommandOuterClass.Command.Param.Builder builderForValue) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.add(builderForValue.build());
          onChanged();
        } else {
          parasBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addParas(
          int index, Report.CommandOuterClass.Command.Param.Builder builderForValue) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.add(index, builderForValue.build());
          onChanged();
        } else {
          parasBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder addAllParas(
          java.lang.Iterable<? extends Report.CommandOuterClass.Command.Param> values) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, paras_);
          onChanged();
        } else {
          parasBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder clearParas() {
        if (parasBuilder_ == null) {
          paras_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          parasBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Builder removeParas(int index) {
        if (parasBuilder_ == null) {
          ensureParasIsMutable();
          paras_.remove(index);
          onChanged();
        } else {
          parasBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.CommandOuterClass.Command.Param.Builder getParasBuilder(
          int index) {
        return getParasFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.CommandOuterClass.Command.ParamOrBuilder getParasOrBuilder(
          int index) {
        if (parasBuilder_ == null) {
          return paras_.get(index);  } else {
          return parasBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public java.util.List<? extends Report.CommandOuterClass.Command.ParamOrBuilder> 
           getParasOrBuilderList() {
        if (parasBuilder_ != null) {
          return parasBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paras_);
        }
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.CommandOuterClass.Command.Param.Builder addParasBuilder() {
        return getParasFieldBuilder().addBuilder(
            Report.CommandOuterClass.Command.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public Report.CommandOuterClass.Command.Param.Builder addParasBuilder(
          int index) {
        return getParasFieldBuilder().addBuilder(
            index, Report.CommandOuterClass.Command.Param.getDefaultInstance());
      }
      /**
       * <code>repeated .Report.Command.Param paras = 2;</code>
       */
      public java.util.List<Report.CommandOuterClass.Command.Param.Builder> 
           getParasBuilderList() {
        return getParasFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Report.CommandOuterClass.Command.Param, Report.CommandOuterClass.Command.Param.Builder, Report.CommandOuterClass.Command.ParamOrBuilder> 
          getParasFieldBuilder() {
        if (parasBuilder_ == null) {
          parasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Report.CommandOuterClass.Command.Param, Report.CommandOuterClass.Command.Param.Builder, Report.CommandOuterClass.Command.ParamOrBuilder>(
                  paras_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          paras_ = null;
        }
        return parasBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Report.Command)
    }

    // @@protoc_insertion_point(class_scope:Report.Command)
    private static final Report.CommandOuterClass.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Report.CommandOuterClass.Command();
    }

    public static Report.CommandOuterClass.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    public Report.CommandOuterClass.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ControlReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Report.ControlReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 tid = 1;</code>
     */
    long getTid();

    /**
     * <code>optional uint32 serial_number = 2;</code>
     */
    int getSerialNumber();

    /**
     * <code>optional .Report.Command command = 3;</code>
     */
    boolean hasCommand();
    /**
     * <code>optional .Report.Command command = 3;</code>
     */
    Report.CommandOuterClass.Command getCommand();
    /**
     * <code>optional .Report.Command command = 3;</code>
     */
    Report.CommandOuterClass.CommandOrBuilder getCommandOrBuilder();
  }
  /**
   * Protobuf type {@code Report.ControlReport}
   */
  public  static final class ControlReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Report.ControlReport)
      ControlReportOrBuilder {
    // Use ControlReport.newBuilder() to construct.
    private ControlReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ControlReport() {
      tid_ = 0L;
      serialNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ControlReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tid_ = input.readUInt64();
              break;
            }
            case 16: {

              serialNumber_ = input.readUInt32();
              break;
            }
            case 26: {
              Report.CommandOuterClass.Command.Builder subBuilder = null;
              if (command_ != null) {
                subBuilder = command_.toBuilder();
              }
              command_ = input.readMessage(Report.CommandOuterClass.Command.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(command_);
                command_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Report.CommandOuterClass.internal_static_Report_ControlReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Report.CommandOuterClass.internal_static_Report_ControlReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Report.CommandOuterClass.ControlReport.class, Report.CommandOuterClass.ControlReport.Builder.class);
    }

    public static final int TID_FIELD_NUMBER = 1;
    private long tid_;
    /**
     * <code>optional uint64 tid = 1;</code>
     */
    public long getTid() {
      return tid_;
    }

    public static final int SERIAL_NUMBER_FIELD_NUMBER = 2;
    private int serialNumber_;
    /**
     * <code>optional uint32 serial_number = 2;</code>
     */
    public int getSerialNumber() {
      return serialNumber_;
    }

    public static final int COMMAND_FIELD_NUMBER = 3;
    private Report.CommandOuterClass.Command command_;
    /**
     * <code>optional .Report.Command command = 3;</code>
     */
    public boolean hasCommand() {
      return command_ != null;
    }
    /**
     * <code>optional .Report.Command command = 3;</code>
     */
    public Report.CommandOuterClass.Command getCommand() {
      return command_ == null ? Report.CommandOuterClass.Command.getDefaultInstance() : command_;
    }
    /**
     * <code>optional .Report.Command command = 3;</code>
     */
    public Report.CommandOuterClass.CommandOrBuilder getCommandOrBuilder() {
      return getCommand();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tid_ != 0L) {
        output.writeUInt64(1, tid_);
      }
      if (serialNumber_ != 0) {
        output.writeUInt32(2, serialNumber_);
      }
      if (command_ != null) {
        output.writeMessage(3, getCommand());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, tid_);
      }
      if (serialNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, serialNumber_);
      }
      if (command_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCommand());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Report.CommandOuterClass.ControlReport)) {
        return super.equals(obj);
      }
      Report.CommandOuterClass.ControlReport other = (Report.CommandOuterClass.ControlReport) obj;

      boolean result = true;
      result = result && (getTid()
          == other.getTid());
      result = result && (getSerialNumber()
          == other.getSerialNumber());
      result = result && (hasCommand() == other.hasCommand());
      if (hasCommand()) {
        result = result && getCommand()
            .equals(other.getCommand());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTid());
      hash = (37 * hash) + SERIAL_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSerialNumber();
      if (hasCommand()) {
        hash = (37 * hash) + COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getCommand().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Report.CommandOuterClass.ControlReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.CommandOuterClass.ControlReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Report.CommandOuterClass.ControlReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Report.CommandOuterClass.ControlReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Report.CommandOuterClass.ControlReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Report.ControlReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Report.ControlReport)
        Report.CommandOuterClass.ControlReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Report.CommandOuterClass.internal_static_Report_ControlReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Report.CommandOuterClass.internal_static_Report_ControlReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Report.CommandOuterClass.ControlReport.class, Report.CommandOuterClass.ControlReport.Builder.class);
      }

      // Construct using Report.CommandOuterClass.ControlReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        tid_ = 0L;

        serialNumber_ = 0;

        if (commandBuilder_ == null) {
          command_ = null;
        } else {
          command_ = null;
          commandBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Report.CommandOuterClass.internal_static_Report_ControlReport_descriptor;
      }

      public Report.CommandOuterClass.ControlReport getDefaultInstanceForType() {
        return Report.CommandOuterClass.ControlReport.getDefaultInstance();
      }

      public Report.CommandOuterClass.ControlReport build() {
        Report.CommandOuterClass.ControlReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Report.CommandOuterClass.ControlReport buildPartial() {
        Report.CommandOuterClass.ControlReport result = new Report.CommandOuterClass.ControlReport(this);
        result.tid_ = tid_;
        result.serialNumber_ = serialNumber_;
        if (commandBuilder_ == null) {
          result.command_ = command_;
        } else {
          result.command_ = commandBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Report.CommandOuterClass.ControlReport) {
          return mergeFrom((Report.CommandOuterClass.ControlReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Report.CommandOuterClass.ControlReport other) {
        if (other == Report.CommandOuterClass.ControlReport.getDefaultInstance()) return this;
        if (other.getTid() != 0L) {
          setTid(other.getTid());
        }
        if (other.getSerialNumber() != 0) {
          setSerialNumber(other.getSerialNumber());
        }
        if (other.hasCommand()) {
          mergeCommand(other.getCommand());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Report.CommandOuterClass.ControlReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Report.CommandOuterClass.ControlReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long tid_ ;
      /**
       * <code>optional uint64 tid = 1;</code>
       */
      public long getTid() {
        return tid_;
      }
      /**
       * <code>optional uint64 tid = 1;</code>
       */
      public Builder setTid(long value) {
        
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 tid = 1;</code>
       */
      public Builder clearTid() {
        
        tid_ = 0L;
        onChanged();
        return this;
      }

      private int serialNumber_ ;
      /**
       * <code>optional uint32 serial_number = 2;</code>
       */
      public int getSerialNumber() {
        return serialNumber_;
      }
      /**
       * <code>optional uint32 serial_number = 2;</code>
       */
      public Builder setSerialNumber(int value) {
        
        serialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 serial_number = 2;</code>
       */
      public Builder clearSerialNumber() {
        
        serialNumber_ = 0;
        onChanged();
        return this;
      }

      private Report.CommandOuterClass.Command command_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Report.CommandOuterClass.Command, Report.CommandOuterClass.Command.Builder, Report.CommandOuterClass.CommandOrBuilder> commandBuilder_;
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public boolean hasCommand() {
        return commandBuilder_ != null || command_ != null;
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Report.CommandOuterClass.Command getCommand() {
        if (commandBuilder_ == null) {
          return command_ == null ? Report.CommandOuterClass.Command.getDefaultInstance() : command_;
        } else {
          return commandBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Builder setCommand(Report.CommandOuterClass.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          command_ = value;
          onChanged();
        } else {
          commandBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Builder setCommand(
          Report.CommandOuterClass.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          command_ = builderForValue.build();
          onChanged();
        } else {
          commandBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Builder mergeCommand(Report.CommandOuterClass.Command value) {
        if (commandBuilder_ == null) {
          if (command_ != null) {
            command_ =
              Report.CommandOuterClass.Command.newBuilder(command_).mergeFrom(value).buildPartial();
          } else {
            command_ = value;
          }
          onChanged();
        } else {
          commandBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Builder clearCommand() {
        if (commandBuilder_ == null) {
          command_ = null;
          onChanged();
        } else {
          command_ = null;
          commandBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Report.CommandOuterClass.Command.Builder getCommandBuilder() {
        
        onChanged();
        return getCommandFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      public Report.CommandOuterClass.CommandOrBuilder getCommandOrBuilder() {
        if (commandBuilder_ != null) {
          return commandBuilder_.getMessageOrBuilder();
        } else {
          return command_ == null ?
              Report.CommandOuterClass.Command.getDefaultInstance() : command_;
        }
      }
      /**
       * <code>optional .Report.Command command = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Report.CommandOuterClass.Command, Report.CommandOuterClass.Command.Builder, Report.CommandOuterClass.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          commandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Report.CommandOuterClass.Command, Report.CommandOuterClass.Command.Builder, Report.CommandOuterClass.CommandOrBuilder>(
                  getCommand(),
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        return commandBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Report.ControlReport)
    }

    // @@protoc_insertion_point(class_scope:Report.ControlReport)
    private static final Report.CommandOuterClass.ControlReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Report.CommandOuterClass.ControlReport();
    }

    public static Report.CommandOuterClass.ControlReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ControlReport>
        PARSER = new com.google.protobuf.AbstractParser<ControlReport>() {
      public ControlReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ControlReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ControlReport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ControlReport> getParserForType() {
      return PARSER;
    }

    public Report.CommandOuterClass.ControlReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_Command_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_Command_Param_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_Command_Param_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Report_ControlReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Report_ControlReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\006Report\"\326\007\n\007Command\022)\n\004t" +
      "ype\030\001 \001(\0162\033.Report.Command.CommandType\022$" +
      "\n\005paras\030\002 \003(\0132\025.Report.Command.Param\032\346\001\n" +
      "\005Param\022,\n\004type\030\001 \001(\0162\036.Report.Command.Pa" +
      "ram.ParaType\022\r\n\005npara\030\002 \001(\004\022\r\n\005dpara\030\003 \001" +
      "(\001\022\017\n\007strpara\030\004 \001(\t\022\r\n\005bpara\030\005 \001(\014\"q\n\010Pa" +
      "raType\022\010\n\004Null\020\000\022\t\n\005UINT8\020\001\022\n\n\006UINT16\020\002\022" +
      "\n\n\006UINT32\020\003\022\n\n\006UINT64\020\004\022\t\n\005FLOAT\020\020\022\n\n\006DO" +
      "UBLE\020\021\022\n\n\006STRING\020 \022\t\n\005BYTES\020!\"\220\005\n\013Comman" +
      "dType\022\017\n\013CMT_INVALID\020\000\022\021\n\rCMT_REQ_LOGIN\020",
      "\001\022\022\n\016CMT_REP_ONLINE\020\002\022\032\n\026CMT_REP_ADD_DEL" +
      "_DEVICE\020\005\022\030\n\024CMT_REP_NOTIFICATION\020\006\022\023\n\017C" +
      "MT_REP_SETNAME\020\010\022\026\n\022CMT_REP_DEL_DEVICE\020\n" +
      "\022\027\n\023CMT_REP_DEVICE_ATTR\020\013\022\026\n\022CMT_REP_DEP" +
      "LOYMENT\020\017\022\021\n\rCMT_REP_ONOFF\020\023\022\031\n\025CMT_REP_" +
      "DEVICE_ONLINE\020\025\022\030\n\024CMT_REP_ONOFF_STATUS\020" +
      "\026\022\027\n\022CMT_REP_DEVICELIST\020\201\020\022\023\n\rCMT_REP_LO" +
      "GIN\020\201\200\002\022\024\n\016CMT_REQ_ONLINE\020\202\200\002\022\025\n\017CMT_REQ" +
      "_SETNAME\020\210\200\002\022\030\n\022CMT_REQ_DEL_DEVICE\020\212\200\002\022\031" +
      "\n\023CMT_REQ_DEVICE_ATTR\020\213\200\002\022\035\n\027CMT_REQ_DEV",
      "ICE_IDENTIFY\020\214\200\002\022\031\n\023CMT_REQ_DEVICE_WARN\020" +
      "\215\200\002\022\030\n\022CMT_REQ_DEPLOYMENT\020\217\200\002\022!\n\033CMT_REQ" +
      "_DEVICE_LEVELCONTROL\020\221\200\002\022\023\n\rCMT_REQ_ONOF" +
      "F\020\223\200\002\022\033\n\025CMT_REQ_DEVICE_ONLINE\020\225\200\002\022\032\n\024CM" +
      "T_REQ_ONOFF_STATUS\020\226\200\002\022\030\n\022CMT_REQ_DEVICE" +
      "LIST\020\201\220\002\"U\n\rControlReport\022\013\n\003tid\030\001 \001(\004\022\025" +
      "\n\rserial_number\030\002 \001(\r\022 \n\007command\030\003 \001(\0132\017" +
      ".Report.Commandb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Report_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Report_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_Command_descriptor,
        new java.lang.String[] { "Type", "Paras", });
    internal_static_Report_Command_Param_descriptor =
      internal_static_Report_Command_descriptor.getNestedTypes().get(0);
    internal_static_Report_Command_Param_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_Command_Param_descriptor,
        new java.lang.String[] { "Type", "Npara", "Dpara", "Strpara", "Bpara", });
    internal_static_Report_ControlReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Report_ControlReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Report_ControlReport_descriptor,
        new java.lang.String[] { "Tid", "SerialNumber", "Command", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
